import {createLife} from './life.js?v=13.1';
import * as THREE from 'three';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=s=>document.querySelector(s), viewport=$('#viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#dfe7e4');
const camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(7.8,6.1,10.8);
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch(e){$('#loading').textContent='3D表示を開始できませんでした。WebGL対応のブラウザで開き直してください。';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;viewport.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.5,0);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=23;controls.maxPolarAngle=Math.PI*.48;controls.minPolarAngle=.15;controls.enablePan=false;
const hemi=new THREE.HemisphereLight(0xe8f8ff,0xb59a7d,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffedcc,3.8);sun.position.set(-3,7,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-7,right:7,top:7,bottom:-7,near:.1,far:25});sun.shadow.normalBias=.025;scene.add(sun);const fill=new THREE.DirectionalLight(0xffffff,1);fill.position.set(4,4,2);scene.add(fill);
const mat=(color,roughness=.8)=>new THREE.MeshStandardMaterial({color,roughness});const wood=mat('#ba885d'),woodLight=mat('#ddb589'),wall=mat('#c5d7d0'),cream=mat('#f4e6c9'),sofaMat=mat('#688e88'),pillowMat=mat('#e6b67f');
function box(w,h,d,m,x,y,z){const a=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;scene.add(a);return a;}
function sphere(x,y,z,sx,sy,sz,m){const a=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),m);a.position.set(x,y,z);a.scale.set(sx,sy,sz);a.castShadow=true;a.receiveShadow=true;scene.add(a);return a;}
function cyl(x,y,z,r,h,m,r2=r){const a=new THREE.Mesh(new THREE.CylinderGeometry(r,r2,h,48),m);a.position.set(x,y,z);a.castShadow=true;a.receiveShadow=true;scene.add(a);return a;}
// Open-plan dollhouse with an accessible kitchen and two reserved sofa seats.
box(10.2,.24,8.2,wood,0,-.15,-.25);for(let i=0;i<20;i++)box(.503,.035,8.1,mat(i%3===0?'#d6b18b':'#dfbd99'),-4.8+i*.505,-.01,-.25);
box(10.2,4.25,.15,wall,0,2.1,-4.35);box(.14,4.25,8.2,wall,-5.1,2.1,-.25);box(10.1,.16,.09,cream,0,.09,-4.24);box(.08,.16,8,cream,-5,.09,-.2);
const sky=new THREE.MeshBasicMaterial({color:0xb9dff0});box(2.25,1.6,.08,sky,.65,2.85,-4.24);for(const x of [-.52,1.82])box(.13,1.8,.15,cream,x,2.85,-4.13);for(const y of [1.98,3.72])box(2.45,.13,.15,cream,.65,y,-4.13);box(.09,1.75,.13,cream,.65,2.85,-4.09);box(2.4,.09,.13,cream,.65,2.85,-4.09);box(2.65,.1,.4,woodLight,.65,1.92,-4.04);
// Sofa wide enough for both full-sized heads, cushions and dangling feet.
box(4.1,.34,1.23,sofaMat,2.12,.59,-2.96);sphere(2.12,1.07,-3.47,2.13,.63,.22,sofaMat);for(const x of [.02,4.22])sphere(x,.89,-2.97,.19,.39,.7,sofaMat);for(const x of [1.12,3.12])sphere(x,.8,-2.9,.97,.14,.59,sofaMat);for(const x of [.35,3.88])for(const z of [-3.45,-2.5])cyl(x,.23,z,.07,.46,wood);sphere(.34,1.1,-3.1,.28,.31,.14,pillowMat).rotation.z=.2;sphere(3.85,1.1,-3.1,.28,.31,.14,cream).rotation.z=-.2;
const rug=cyl(.25,.025,1.03,3.1,.045,mat('#c78970'));rug.scale.z=.66;const rugInner=cyl(.25,.052,1.03,2.91,.01,mat('#e7c3a5'));rugInner.scale.z=.65;
// Kitchen base, countertop, sink, faucet and backsplash.
const cabinet=mat('#8ca49a'),tile=mat('#ecede3'),metal=mat('#9caba8',.28);box(2.22,1.17,1.05,cabinet,-1.66,.6,-3.69);box(2.34,.12,1.17,cream,-1.66,1.24,-3.64);
for(const x of [-2.19,-1.1]){box(1.03,.91,.045,mat('#9ab1a7'),x,.63,-3.14);box(.28,.035,.065,metal,x,1,-3.09);}for(let i=0;i<7;i++)for(let j=0;j<3;j++)box(.31,.26,.035,tile,-2.64+i*.327,1.48+j*.28,-4.24);
box(.79,.025,.62,metal,-1.82,1.315,-3.6);box(.65,.035,.48,mat('#516c70'),-1.82,1.33,-3.59);cyl(-1.82,1.53,-3.98,.035,.43,metal);const tap=box(.23,.06,.06,metal,-1.72,1.74,-3.98);cyl(-1.61,1.69,-3.98,.035,.1,metal);box(.45,.05,.5,woodLight,-.91,1.335,-3.62);
box(1.18,.08,.45,woodLight,-1.77,2.64,-4.03);for(let i=0;i<3;i++)cyl(-2.1+i*.3,2.83,-4.01,.085,.28,mat(['#e6c194','#bac7b4','#e7e5d9'][i]));
// Fridge is a hollow cabinet with shelves and a hinged door, not a solid block.
const fridgeMat=mat('#e5ebe1'),fridgeInside=mat('#f2f0e6');const fx=-3.75,fz=-3.65;box(1.57,2.9,.12,fridgeMat,fx,1.5,-4.21);for(const x of [fx-.74,fx+.74])box(.1,2.9,1.14,fridgeMat,x,1.5,fz);for(const y of [.09,2.92])box(1.55,.1,1.2,fridgeMat,fx,y,fz);for(const y of [.65,1.35,2.07])box(1.4,.045,.92,fridgeInside,fx,y,-3.65);
for(const y of [.83,1.54])for(const x of [fx-.35,fx+.05,fx+.38]){cyl(x,y+.06,-3.67,.075,.28,mat(x<fx?'#d0ae70':'#bcc9a6'));cyl(x,y+.22,-3.67,.045,.06,cream);}
const fridgeDoor=new THREE.Group();fridgeDoor.position.set(fx-.8,.04,-3.02);scene.add(fridgeDoor);
function doorBox(w,h,d,m,x,y,z){const a=box(w,h,d,m,0,0,0);fridgeDoor.add(a);a.position.set(x,y,z);return a;}
doorBox(1.58,2.89,.13,fridgeMat,.79,1.445,0);doorBox(.055,.65,.1,woodLight,1.4,1.37,.11);doorBox(1.49,.025,.02,metal,.79,2.15,.076);doorBox(.18,.15,.025,mat('#d7a46d'),.48,2.49,.09);doorBox(.13,.13,.025,sofaMat,.69,2.55,.09);
// Low side table and a floor lamp.
cyl(4.29,.66,1.86,.43,.09,woodLight);cyl(4.29,.32,1.86,.055,.64,wood);cyl(4.29,.06,1.86,.23,.06,wood);cyl(4.3,.83,1.86,.1,.22,mat('#cf8f6f'),.08);for(let i=0;i<5;i++)sphere(4.3+Math.sin(i*2)*.1,1.06+Math.cos(i)*.05,1.86+Math.cos(i*2)*.09,.06,.17,.04,mat('#62896c')).rotation.z=Math.sin(i)*.7;
cyl(4.58,.06,-3.71,.27,.09,mat('#566567'));cyl(4.58,1.25,-3.71,.034,2.45,wood);const shade=mat('#f4d7a3');shade.emissive=new THREE.Color('#f3ba69');shade.emissiveIntensity=.08;cyl(4.58,2.5,-3.71,.27,.43,shade,.44);const lamp=new THREE.PointLight(0xffb969,0,7);lamp.position.set(4.58,2.3,-3.71);scene.add(lamp);
box(.85,1.08,.09,wood,3.31,2.73,-4.21);box(.7,.93,.035,cream,3.31,2.73,-4.15);sphere(3.31,2.8,-4.12,.23,.23,.016,mat('#d29b64'));box(.52,.08,.025,sofaMat,3.31,2.43,-4.1);
const characters=[];let life,paused=false,currentLight='day',currentView='room';const clock=new THREE.Clock();
function playClip(c,mode){c.mixer.stopAllAction();if(c.bones)for(const [n,b]of Object.entries(c.bones)){b.quaternion.copy(c.rest[n]);b.scale.copy(c.restScale[n]);}c.mode=mode;const name={walk:'Walk_PitterPatter',dance:'Dance_Bounce',paws:'Paws_Up'}[mode];if(name){const clip=c.clips.find(a=>a.name===name);if(clip)c.mixer.clipAction(clip).reset().play();}c.mixer.update(0);}
function status(i,text){$('#'+(i?'juli':'eido')+'-status').textContent=text;}
function modeButtons(isAuto){document.querySelectorAll('#together button').forEach(b=>b.classList.toggle('active',b.dataset.mode===(isAuto?'auto':'pose')));}
async function loadModels(){const loader=new GLTFLoader();const gltfs=await Promise.all(['eidotown-v13','julitown'].map(n=>loader.loadAsync('./models/'+n+'.glb')));gltfs.forEach((g,i)=>{const outer=new THREE.Group(),model=g.scene;outer.add(model);scene.add(outer);model.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(model),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());const scale=1.85/size.y;model.scale.multiplyScalar(scale);model.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});characters.push({outer,model,mixer:new THREE.AnimationMixer(model),clips:g.animations,mode:'idle'});});life=createLife({characters,scene,fridge:fridgeDoor,playClip,onStatus:status,onMode:modeButtons});$('#loading').classList.add('hidden');$('#actions').disabled=false;$('#capture').disabled=false;document.body.dataset.ready='true';}
function setLight(mode){if(!['day','sunset','night'].includes(mode))throw Error('あかりを選んでください');currentLight=mode;const conf={day:[0xdfe7e4,0xffedcc,3.8,2.2,0,0xb9dff0,1.12],sunset:[0xe4c7b8,0xffac70,3,1.45,1,0xe7ad8e,1.05],night:[0x263847,0xa7c7ff,.65,.7,3.5,0x243855,.95]}[mode];scene.background.setHex(conf[0]);sun.color.setHex(conf[1]);sun.intensity=conf[2];hemi.intensity=conf[3];lamp.intensity=conf[4];sky.color.setHex(conf[5]);shade.emissiveIntensity=mode==='night'?.8:.08;renderer.toneMappingExposure=conf[6];document.querySelectorAll('#lights button').forEach(b=>b.classList.toggle('active',b.dataset.light===mode));}
function setView(mode){if(!['room','front','close','kitchen','sofa'].includes(mode))throw Error('視点を選んでください');currentView=mode;const p={room:[9.4,7.6,13.2],front:[0,4,14],close:[.3,2.8,7.6],kitchen:[-1.1,3.2,3.8],sofa:[5.3,3.6,4.2]}[mode];camera.position.set(...p);const target={room:[0,1.3,-.45],front:[0,1.5,-.8],close:[0,1.1,1],kitchen:[-3,1.2,-2.75],sofa:[2.1,1.25,-2.6]}[mode];controls.target.set(...target);controls.update();document.querySelectorAll('#views button').forEach(b=>b.classList.toggle('active',b.dataset.view===mode));}
$('#together').addEventListener('click',e=>{const b=e.target.closest('button');if(b&&life){life.setTogether(b.dataset.mode);document.querySelectorAll('#together button').forEach(x=>x.classList.toggle('active',x===b));}});['eido','juli'].forEach((n,i)=>$('#'+n+'-action').addEventListener('change',e=>{life.request(i,e.target.value);e.target.value='auto';}));$('#pause').onclick=()=>{paused=!paused;life?.setPaused(paused);$('#pause').textContent=paused?'暮らしを再開':'動きを止める';$('#pause').setAttribute('aria-pressed',String(paused));};$('#lights').onclick=e=>{const b=e.target.closest('button');if(b)setLight(b.dataset.light);};$('#views').onclick=e=>{const b=e.target.closest('button');if(b)setView(b.dataset.view);};$('#reset').onclick=()=>setView('room');
let photoUrl;$('#capture').onclick=async()=>{const button=$('#capture');button.disabled=true;try{renderer.render(scene,camera);const blob=await new Promise(resolve=>renderer.domElement.toBlob(resolve,'image/png'));if(!blob)throw Error('撮影できませんでした');if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=URL.createObjectURL(blob);$('#photo').src=photoUrl;$('#download').href=photoUrl;$('#download').download='eido-juli-'+new Date().toISOString().replace(/[:.]/g,'-')+'.png';$('#flash').classList.remove('shoot');void $('#flash').offsetWidth;$('#flash').classList.add('shoot');$('#photo-dialog').showModal();}catch(e){$('#message').textContent='撮影できませんでした。もう一度お試しください。';}finally{button.disabled=false;}};$('#close-photo').onclick=()=>$('#photo-dialog').close();$('#photo-dialog').addEventListener('click',e=>{if(e.target===$('#photo-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
new ResizeObserver(()=>{const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}).observe(viewport);
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.06);life?.tick(dt);controls.update();renderer.render(scene,camera);}setView('room');animate();loadModels().catch(e=>{$('#loading').textContent='モデルを読み込めませんでした。ページを再読み込みしてください。';console.error(e);});
if(document.modelContext?.registerTool){const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{});}catch{}};register({name:'read_room',description:'ふたりの現在の行動、位置、冷蔵庫の扉の状態を確認します。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(){return life?.getState()??{loading:true};}});register({name:'configure_room',description:'おまかせ生活・記念撮影への切り替え、個別の行動リクエスト、あかりや視点の変更。',inputSchema:{type:'object',properties:{action:{type:'string',enum:['auto','pose','dance']},character:{type:'integer',enum:[0,1]},activity:{type:'string',enum:['auto','walk','sit','drink','dance']},light:{type:'string',enum:['day','sunset','night']},view:{type:'string',enum:['room','front','close','kitchen','sofa']},paused:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['action','character','activity','light','view','paused'].includes(k)))throw Error('入力が不正です');for(const [k,values]of Object.entries({action:['auto','pose','dance'],character:[0,1],activity:['auto','walk','sit','drink','dance'],light:['day','sunset','night'],view:['room','front','close','kitchen','sofa']}))if(k in input&&!values.includes(input[k]))throw Error('選択肢が不正です');if('paused'in input&&typeof input.paused!=='boolean'||('activity'in input)!==('character'in input))throw Error('入力が不正です');if(!life)throw Error('読み込み中です');if(input.action)life.setTogether(input.action);if(input.activity)life.request(input.character,input.activity);if(input.light)setLight(input.light);if(input.view)setView(input.view);if('paused'in input){paused=input.paused;life.setPaused(paused);$('#pause').textContent=paused?'暮らしを再開':'動きを止める';$('#pause').setAttribute('aria-pressed',String(paused));}return{...life.getState(),light:currentLight,view:currentView};}});}
