import * as THREE from './vendor/three.module.js';
const clamp=THREE.MathUtils.clamp, smooth=t=>{t=clamp(t,0,1);return t*t*(3-2*t);};
const labels={idle:'のんびり',walk:'おさんぽ中',approachSeat:'ソファへ',sitDown:'よいしょ…',sit:'ソファでくつろぎ中',standUp:'おさんぽに戻るところ',approachFridge:'冷蔵庫へ',openFridge:'冷蔵庫を開けています',takeDrink:'飲み物を選んでいます',closeFridge:'冷蔵庫を閉めています',drink:'飲み物でひと休み',dance:'ダンス中',pose:'記念撮影'};
export function createLife({characters,scene,fridge,playClip,onStatus,onMode}){
 let time=0,paused=false,auto=true,fridgeOwner=null,doorAngle=0;const seats=[{x:1.15,z:-2.58,owner:null},{x:3.12,z:-2.58,owner:null}];const rand=(a,b)=>a+Math.random()*(b-a);const status={};
 function setState(c,state,duration=0){c.state=state;c.timer=0;c.duration=duration;c.start=c.outer.position.clone();const walking=['walk','approachSeat','approachFridge'].includes(state);playClip(c,walking?'walk':state==='dance'?'dance':'idle');if(status[c.index]!==labels[state]){status[c.index]=labels[state];onStatus(c.index,labels[state]);}}
 function turn(c,angle,dt){let d=THREE.MathUtils.euclideanModulo(angle-c.outer.rotation.y+Math.PI,Math.PI*2)-Math.PI;c.outer.rotation.y+=d*Math.min(1,dt*5);}
 function reserveRelease(c){if(c.seat!=null){seats[c.seat].owner=null;c.seat=null;}if(fridgeOwner===c.index)fridgeOwner=null;}
 function walk(c,x,z,next='idle'){c.target=new THREE.Vector3(x,.065,z);c.next=next;setState(c,next==='sitDown'?'approachSeat':next==='openFridge'?'approachFridge':'walk');}
 function wander(c){let x,z;for(let j=0;j<20;j++){x=rand(-3.8,3.85);z=rand(-.95,2.75);if(characters.every(o=>o===c||Math.hypot(x-o.outer.position.x,z-o.outer.position.z)>1.55))break;}walk(c,x,z);}
 function plan(c,choice){if(choice==='sit'){const j=seats.findIndex(s=>s.owner===null);if(j>=0){c.seat=j;seats[j].owner=c.index;walk(c,seats[j].x,-1.15,'sitDown');return;}}if(choice==='drink'&&fridgeOwner===null){fridgeOwner=c.index;walk(c,-3.65,-1.6,'openFridge');return;}if(choice==='dance'){setState(c,'dance',rand(9,15));return;}wander(c);}
 function decide(c){const r=Math.random();plan(c,r<.36?'sit':r<.64?'drink':'walk');}
 function rotateBone(c,name,x=0,y=0,z=0){name=name.replaceAll('.','');const b=c.bones[name];if(!b)return;b.quaternion.copy(c.rest[name]).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(x,y,z)));}
 function resting(c,amount){rotateBone(c,'leg.L',-.95*amount);rotateBone(c,'leg.R',-.95*amount);rotateBone(c,'torso',-.07*amount);rotateBone(c,'head',.055*amount,Math.sin(time*.5+c.index)*.1*amount);rotateBone(c,'arm.L',.1*amount,0,-.12*amount);rotateBone(c,'arm.R',.1*amount,0,.12*amount);}
 function holdCup(c){const b=c.bones.armR;if(!b)return;c.outer.updateMatrixWorld(true);const offset=new THREE.Vector3(-.075,-.04,-.105).applyAxisAngle(new THREE.Vector3(0,1,0),c.outer.rotation.y);const target=c.cup.position.clone().add(offset);const origin=b.getWorldPosition(new THREE.Vector3());const direction=target.sub(origin);const desired=new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),direction.clone().normalize());const parent=b.parent.getWorldQuaternion(new THREE.Quaternion()).invert();b.quaternion.copy(parent.multiply(desired));b.scale.y=c.restScale.armR.y*Math.min(1.3,Math.max(1,direction.length()/.3));}
 function cup(){const g=new THREE.Group(),m=new THREE.MeshStandardMaterial({color:'#d89571',roughness:.65});const outer=new THREE.Mesh(new THREE.CylinderGeometry(.12,.1,.22,32,1,true),m);outer.castShadow=true;g.add(outer);const tea=new THREE.Mesh(new THREE.CircleGeometry(.102,32),new THREE.MeshStandardMaterial({color:'#6d3f24',roughness:.2}));tea.rotation.x=-Math.PI/2;tea.position.y=.075;g.add(tea);const handle=new THREE.Mesh(new THREE.TorusGeometry(.072,.018,10,24),m);handle.position.x=.125;g.add(handle);g.visible=false;scene.add(g);return g;}
 characters.forEach((c,i)=>{c.index=i;c.seat=null;c.bones={};c.rest={};c.restScale={};c.model.traverse(o=>{if(o.isBone){c.bones[o.name]=o;c.rest[o.name]=o.quaternion.clone();c.restScale[o.name]=o.scale.clone();}});c.cup=cup();c.outer.position.set(i?1.5:-1.7,.065,1.4);c.outer.rotation.y=i?-.25:.25;setState(c,'idle',i?3:1);c.first=i?'drink':'sit';});
 function request(i,choice){const c=characters[i];if(!c)return;if(choice==='auto'){auto=true;onMode(true);c.pending=null;if(c.state==='pose'||c.state==='dance')setState(c,'idle',1);return;}if(!auto)setAuto(true);auto=true;onMode(true);c.pending=choice;if(['idle','walk','dance','pose'].includes(c.state)){reserveRelease(c);c.pending=null;plan(c,choice);}else if(c.state==='sit'){c.duration=Math.min(c.duration,c.timer+1);}}
 function setAuto(value){auto=value;if(!value){doorAngle=0;fridge.rotation.y=0;}onMode(value);characters.forEach(c=>{if(!value){reserveRelease(c);c.cup.visible=false;c.outer.position.set(c.index?.95:-.95,.065,1.05);c.outer.rotation.y=0;setState(c,'pose');}else if(c.state==='pose')setState(c,'idle',rand(1,3));});}
 function setTogether(choice){if(choice==='auto'){setAuto(true);return;}setAuto(false);characters.forEach(c=>{if(choice==='dance')setState(c,'dance',Infinity);});}
 function tick(dt){if(paused)return;time+=dt;let wantDoor=0;
  for(const c of characters){c.timer+=dt;const t=c.timer;let walking=['walk','approachSeat','approachFridge'].includes(c.state);c.mixer.update(dt);
   if(walking){const delta=c.target.clone().sub(c.outer.position);delta.y=0;const dist=delta.length();if(dist<.06){c.outer.position.copy(c.target);if(c.next==='sitDown')setState(c,'sitDown',1.7);else if(c.next==='openFridge')setState(c,'openFridge',2);else setState(c,'idle',rand(2,5));}else{delta.normalize();const step=.58*dt;const other=characters.find(o=>o!==c);if(other){const diff=c.outer.position.clone().sub(other.outer.position);diff.y=0;const d=diff.length();if(d<1.5&&d>.01&&delta.dot(diff)<.2){const side=new THREE.Vector3(-delta.z,0,delta.x);delta.addScaledVector(side,(1.5-d)*2).normalize();}}const candidate=c.outer.position.clone().addScaledVector(delta,Math.min(step,dist));if(!other||candidate.distanceTo(other.outer.position)>1.45||candidate.distanceTo(other.outer.position)>=c.outer.position.distanceTo(other.outer.position))c.outer.position.copy(candidate);else{const away=c.outer.position.clone().sub(other.outer.position);away.y=0;away.normalize();const tangent=new THREE.Vector3(-away.z,0,away.x).addScaledVector(away,.08).normalize();c.outer.position.addScaledVector(tangent,step);delta.copy(tangent);}c.outer.position.x=clamp(c.outer.position.x,-4.05,4.1);c.outer.position.z=clamp(c.outer.position.z,-1.65,2.95);turn(c,Math.atan2(delta.x,delta.z),dt);}}
   else if(c.state==='idle'){rotateBone(c,'head',0,Math.sin(time*.55+c.index)*.16,0);if(auto&&t>c.duration){const next=c.pending||c.first;c.pending=null;c.first=null;next?plan(c,next):decide(c);}}
   else if(c.state==='sitDown'){const seat=seats[c.seat],u=smooth(t/1.7);c.outer.position.lerpVectors(c.start,new THREE.Vector3(seat.x,.78,seat.z),u);c.outer.position.y+=Math.sin(Math.PI*u)*.18;turn(c,0,dt);resting(c,u);if(t>1.7)setState(c,'sit',rand(14,26));}
   else if(c.state==='sit'){resting(c,1);turn(c,0,dt);if(t>c.duration)setState(c,'standUp',1.6);}
   else if(c.state==='standUp'){const u=smooth(t/1.6);c.outer.position.lerpVectors(c.start,new THREE.Vector3(seats[c.seat].x,.065,-1.15),u);c.outer.position.y+=Math.sin(Math.PI*u)*.14;resting(c,1-u);if(t>1.6){reserveRelease(c);setState(c,'idle',2);}}
   else if(c.state==='openFridge'){turn(c,Math.PI,dt);rotateBone(c,'arm.R',-.5*smooth(t),0,.45*smooth(t));wantDoor=1.65*smooth(t/1.5);if(t>2)setState(c,'takeDrink',2.6);}
   else if(c.state==='takeDrink'){turn(c,Math.PI,dt);wantDoor=1.65;rotateBone(c,'arm.R',-.85,0,.6);if(t>1)c.cup.visible=true;const p=new THREE.Vector3(-.36,.9,.52).applyAxisAngle(new THREE.Vector3(0,1,0),c.outer.rotation.y).add(c.outer.position);c.cup.position.copy(p);if(t>2.6)setState(c,'closeFridge',1.8);}
   else if(c.state==='closeFridge'){wantDoor=1.65*(1-smooth(t/1.6));rotateBone(c,'arm.R',-.65,0,.4);if(t>1.8){fridgeOwner=null;setState(c,'drink',9);}}
   else if(c.state==='drink'){turn(c,Math.PI*.12,dt);const sip=smooth(Math.sin(Math.PI*clamp((t-1)/6,0,1)));rotateBone(c,'arm.R',-.7-.9*sip,0,.3+.25*sip);rotateBone(c,'head',-.055*sip);const p=new THREE.Vector3(-.24+.14*sip,.72+.13*sip,.40+.17*sip).applyAxisAngle(new THREE.Vector3(0,1,0),c.outer.rotation.y).add(c.outer.position);c.cup.position.copy(p);c.cup.rotation.set(-.45*sip,c.outer.rotation.y,0);if(t>c.duration){c.cup.visible=false;setState(c,'idle',rand(2,4));}}
   else if(c.state==='dance'&&auto&&t>c.duration)setState(c,'idle',2);
   if(c.cup.visible&&['takeDrink','closeFridge','drink'].includes(c.state))holdCup(c);
   const blinkPhase=(time+c.index*2.8)%5.4;const blink=blinkPhase<.16?Math.sin(blinkPhase/.16*Math.PI):0;c.model.traverse(o=>{if(o.morphTargetDictionary&&o.morphTargetInfluences){for(const [n,k]of Object.entries(o.morphTargetDictionary)){if(/blink/i.test(n))o.morphTargetInfluences[k]=blink;}}});
  }
  // Gentle separation in the open floor, without moving seated characters or kitchen interactions.
  const a=characters[0],b=characters[1];if(a&&b){const d=a.outer.position.clone().sub(b.outer.position);d.y=0;const n=d.length();if(n>0&&n<1.45){const movable=c=>['idle','walk','approachSeat','approachFridge','dance','pose'].includes(c.state);const ma=movable(a),mb=movable(b);if(ma||mb){d.multiplyScalar((1.45-n)/n/(ma&&mb?2:1));if(ma)a.outer.position.add(d);if(mb)b.outer.position.sub(d);}}}
  doorAngle=THREE.MathUtils.damp(doorAngle,wantDoor,8,dt);fridge.rotation.y=-doorAngle;
 }
 return{tick,request,setTogether,setAuto,setPaused(v){paused=v;},getState(){return{auto,paused,characters:characters.map(c=>({name:c.index?'じゅりたうん':'えいどたうん',state:c.state,position:c.outer.position.toArray()})),fridgeOpen:doorAngle};}};
}
